### ISSUE TITLE
0.7.4 release

### ISSUE THREAD

**Issue by palfrey** [unintended/Cohen#10]
Guessing this was intended given c5342376cec78e031d29e9cf806dfd25bb861f4c but https://travis-ci.org/unintended/Cohen/builds/587912311 has "Skipping a deployment with the pypi provider because this is not a tagged commit" at the end for some reason...

**Comment by unintended** [comment]
Got it, thanks https://pypi.org/project/Cohen/0.7.4/

I just don't have much time to maintain the project well, sorry for that

**Comment by palfrey** [comment]
No worries. At some point I'll be moving over to using the Python 3 one instead, but currently this has been really useful for a piece of software I'm writing that uses Coherence, so thanks for yuour work to make it do anything at all TBH.
